import {
  AlarmEvent,
  CleaningCrew,
  Container,
  DashboardSummary,
  Device,
  MaintenanceTicket,
  RoutePlan,
  TelemetryPoint,
} from "@/types";

const now = new Date();
const ago = (minutes: number) =>
  new Date(now.getTime() - minutes * 60 * 1000).toISOString();
const from_now = (minutes: number) =>
  new Date(now.getTime() + minutes * 60 * 1000).toISOString();
const today = now.toISOString().split("T")[0];

// ── Containers ────────────────────────────────────────────────────────────────

export const MOCK_CONTAINERS: Container[] = [
  {
    container_id: "cont-001",
    name: "Trg Republike 1",
    site_id: "site-center",
    address: "Trg Republike 1, Beograd",
    location: { type: "Point", coordinates: [20.4584, 44.8152] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000, max_payload_kg: 500 },
    assigned_device_id: "dev-001",
    latest_state: {
      last_seen_at: ago(2),
      fused_fill_pct: 87,
      fill_state: "FULL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 22.1,
      humidity_pct: 61,
      light_lux: 450,
      weight_kg: 320,
      ultrasonic_distance_cm: 35,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-002",
    name: "Knez Mihailova 12",
    site_id: "site-center",
    address: "Knez Mihailova 12, Beograd",
    location: { type: "Point", coordinates: [20.4566, 44.8198] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000, max_payload_kg: 500 },
    assigned_device_id: "dev-002",
    latest_state: {
      last_seen_at: ago(5),
      fused_fill_pct: 96,
      fill_state: "CRITICAL",
      camera_state: "GARBAGE_DETECTED",
      flame_detected: false,
      temperature_c: 21.8,
      humidity_pct: 58,
      light_lux: 510,
      weight_kg: 445,
      ultrasonic_distance_cm: 12,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-003",
    name: "Terazije 5",
    site_id: "site-center",
    address: "Terazije 5, Beograd",
    location: { type: "Point", coordinates: [20.4602, 44.8145] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 2500 },
    assigned_device_id: "dev-003",
    latest_state: {
      last_seen_at: ago(8),
      fused_fill_pct: 65,
      fill_state: "NEAR_FULL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 23.5,
      humidity_pct: 55,
      weight_kg: 280,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-004",
    name: "Bulevar Kralja Aleksandra 47",
    site_id: "site-vracar",
    address: "Bulevar Kralja Aleksandra 47, Beograd",
    location: { type: "Point", coordinates: [20.4731, 44.8098] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000, max_payload_kg: 500 },
    assigned_device_id: "dev-004",
    latest_state: {
      last_seen_at: ago(15),
      fused_fill_pct: 42,
      fill_state: "NORMAL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 20.8,
      humidity_pct: 63,
      weight_kg: 190,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-005",
    name: "Slavija Trg 3",
    site_id: "site-vracar",
    address: "Slavija Trg 3, Beograd",
    location: { type: "Point", coordinates: [20.4699, 44.8058] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000 },
    assigned_device_id: "dev-005",
    latest_state: {
      last_seen_at: ago(1),
      fused_fill_pct: 13,
      fill_state: "EMPTY",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 19.2,
      humidity_pct: 68,
      weight_kg: 45,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-006",
    name: "Nemanjina 22",
    site_id: "site-savski-venac",
    address: "Nemanjina 22, Beograd",
    location: { type: "Point", coordinates: [20.4505, 44.8052] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000, max_payload_kg: 500 },
    assigned_device_id: "dev-006",
    latest_state: {
      last_seen_at: ago(120),
      fused_fill_pct: 78,
      fill_state: "NEAR_FULL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 18.1,
      humidity_pct: 72,
      device_status: "OFFLINE",
    },
  },
  {
    container_id: "cont-007",
    name: "Vojvode Stepe 101",
    site_id: "site-vozdovac",
    address: "Vojvode Stepe 101, Beograd",
    location: { type: "Point", coordinates: [20.4823, 44.7901] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000 },
    assigned_device_id: "dev-007",
    latest_state: {
      last_seen_at: ago(3),
      fused_fill_pct: 91,
      fill_state: "CRITICAL",
      camera_state: "GARBAGE_DETECTED",
      flame_detected: true,
      flame_intensity_pct: 34,
      temperature_c: 52.3,
      humidity_pct: 40,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-008",
    name: "Autokomanda 7",
    site_id: "site-vozdovac",
    address: "Autokomanda 7, Beograd",
    location: { type: "Point", coordinates: [20.4889, 44.7955] },
    status: "MAINTENANCE",
    container_type: "UNDERGROUND",
    assigned_device_id: "dev-008",
    latest_state: {
      last_seen_at: ago(240),
      fused_fill_pct: 55,
      fill_state: "NORMAL",
      camera_state: "CAMERA_FAULT",
      flame_detected: false,
      device_status: "FAULT",
    },
  },
  {
    container_id: "cont-009",
    name: "Zemun — Gardoš 4",
    site_id: "site-zemun",
    address: "Gardoš 4, Zemun",
    location: { type: "Point", coordinates: [20.4012, 44.8453] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 2500 },
    assigned_device_id: "dev-009",
    latest_state: {
      last_seen_at: ago(10),
      fused_fill_pct: 50,
      fill_state: "NORMAL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 21.0,
      humidity_pct: 60,
      weight_kg: 220,
      device_status: "DEGRADED",
    },
  },
  {
    container_id: "cont-010",
    name: "Zemun — Cara Dušana 32",
    site_id: "site-zemun",
    address: "Cara Dušana 32, Zemun",
    location: { type: "Point", coordinates: [20.4051, 44.8412] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000, max_payload_kg: 500 },
    assigned_device_id: "dev-010",
    latest_state: {
      last_seen_at: ago(7),
      fused_fill_pct: 76,
      fill_state: "NEAR_FULL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 22.5,
      humidity_pct: 57,
      weight_kg: 310,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-011",
    name: "Novi Beograd — Blok 45",
    site_id: "site-novi-beograd",
    address: "Blok 45, Novi Beograd",
    location: { type: "Point", coordinates: [20.4131, 44.8098] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000 },
    assigned_device_id: "dev-011",
    latest_state: {
      last_seen_at: ago(6),
      fused_fill_pct: 85,
      fill_state: "FULL",
      camera_state: "GARBAGE_DETECTED",
      flame_detected: false,
      temperature_c: 20.3,
      humidity_pct: 64,
      weight_kg: 380,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-012",
    name: "Novi Beograd — Gandijeva 3",
    site_id: "site-novi-beograd",
    address: "Gandijeva 3, Novi Beograd",
    location: { type: "Point", coordinates: [20.4200, 44.8055] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000 },
    assigned_device_id: "dev-012",
    latest_state: {
      last_seen_at: ago(18),
      fused_fill_pct: 30,
      fill_state: "NORMAL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 19.8,
      humidity_pct: 66,
      weight_kg: 130,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-013",
    name: "Dorćol — Cara Dušana 12",
    site_id: "site-stari-grad",
    address: "Cara Dušana 12, Beograd",
    location: { type: "Point", coordinates: [20.4640, 44.8237] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 2500 },
    assigned_device_id: "dev-013",
    latest_state: {
      last_seen_at: ago(4),
      fused_fill_pct: 25,
      fill_state: "NORMAL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 21.4,
      humidity_pct: 59,
      weight_kg: 110,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-014",
    name: "Bežanija — Tošin Bunar 85",
    site_id: "site-novi-beograd",
    address: "Tošin Bunar 85, Beograd",
    location: { type: "Point", coordinates: [20.3820, 44.8199] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    assigned_device_id: "dev-014",
    latest_state: {
      last_seen_at: ago(9),
      fused_fill_pct: 58,
      fill_state: "NORMAL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 20.0,
      humidity_pct: 62,
      device_status: "ONLINE",
    },
  },
  {
    container_id: "cont-015",
    name: "Palilula — Cara Nikolaja 8",
    site_id: "site-palilula",
    address: "Cara Nikolaja 8, Beograd",
    location: { type: "Point", coordinates: [20.4852, 44.8295] },
    status: "ACTIVE",
    container_type: "UNDERGROUND",
    capacity: { volume_l: 3000, max_payload_kg: 500 },
    assigned_device_id: "dev-015",
    latest_state: {
      last_seen_at: ago(11),
      fused_fill_pct: 89,
      fill_state: "FULL",
      camera_state: "EVERYTHING_OK",
      flame_detected: false,
      temperature_c: 22.8,
      humidity_pct: 56,
      weight_kg: 395,
      device_status: "ONLINE",
    },
  },
];

export const MOCK_DEVICES: Device[] = MOCK_CONTAINERS.map((container, index) => ({
  device_id: container.assigned_device_id ?? `dev-${String(index + 1).padStart(3, "0")}`,
  factory_device_id: `unoq-${String(index + 1).padStart(3, "0")}`,
  container_id: container.container_id,
  status: container.latest_state.device_status ?? "UNKNOWN",
  last_seen_at: container.latest_state.last_seen_at,
  created_at: ago(24 * 60),
  firmware: {
    mcu_version: "0.1.0",
    linux_app_version: "0.1.0",
    model_id: "garbage-classifier-v1",
  },
  capabilities: {
    sensors: ["temperature", "humidity", "light", "ultrasonic", "weight", "tamper"],
    camera: true,
    offline_buffer: true,
  },
}));

// ── Alarms ─────────────────────────────────────────────────────────────────────

export const MOCK_ALARMS: AlarmEvent[] = [
  {
    event_id: "evt-001",
    container_id: "cont-002",
    type: "CRITICAL_FULL",
    severity: "CRITICAL",
    status: "OPEN",
    started_at: ago(30),
    summary: "Container at 96% capacity — requires immediate collection.",
    location: { lat: 44.8198, lng: 20.4566 },
  },
  {
    event_id: "evt-002",
    container_id: "cont-007",
    type: "FLAME_DETECTED",
    severity: "CRITICAL",
    status: "OPEN",
    started_at: ago(12),
    summary: "Flame signal detected at 34% intensity. Container temperature 52°C.",
    location: { lat: 44.7901, lng: 20.4823 },
  },
  {
    event_id: "evt-003",
    container_id: "cont-007",
    type: "GARBAGE_DETECTED",
    severity: "WARNING",
    status: "OPEN",
    started_at: ago(45),
    summary: "Camera detected garbage outside container.",
    location: { lat: 44.7901, lng: 20.4823 },
  },
  {
    event_id: "evt-004",
    container_id: "cont-002",
    type: "GARBAGE_DETECTED",
    severity: "WARNING",
    status: "ACKNOWLEDGED",
    started_at: ago(90),
    summary: "Camera confirmed garbage spill detected.",
    location: { lat: 44.8198, lng: 20.4566 },
  },
  {
    event_id: "evt-005",
    container_id: "cont-006",
    type: "DEVICE_OFFLINE",
    severity: "WARNING",
    status: "OPEN",
    started_at: ago(120),
    summary: "Device has not sent heartbeat for 2 hours.",
    location: { lat: 44.8052, lng: 20.4505 },
  },
  {
    event_id: "evt-006",
    container_id: "cont-008",
    type: "CAMERA_FAULT",
    severity: "WARNING",
    status: "OPEN",
    started_at: ago(200),
    summary: "Camera inference failed 5 times consecutively.",
    location: { lat: 44.7955, lng: 20.4889 },
  },
  {
    event_id: "evt-007",
    container_id: "cont-001",
    type: "FULL_THRESHOLD",
    severity: "WARNING",
    status: "OPEN",
    started_at: ago(60),
    summary: "Container fill reached 87% — scheduled for next collection.",
    location: { lat: 44.8152, lng: 20.4584 },
  },
  {
    event_id: "evt-008",
    container_id: "cont-011",
    type: "GARBAGE_DETECTED",
    severity: "WARNING",
    status: "OPEN",
    started_at: ago(25),
    summary: "Camera detected waste accumulation near container opening.",
    location: { lat: 44.8098, lng: 20.4131 },
  },
  {
    event_id: "evt-009",
    container_id: "cont-015",
    type: "FULL_THRESHOLD",
    severity: "WARNING",
    status: "ACKNOWLEDGED",
    started_at: ago(80),
    summary: "Container fill at 89%, approaching critical threshold.",
    location: { lat: 44.8295, lng: 20.4852 },
  },
  {
    event_id: "evt-010",
    container_id: "cont-003",
    type: "GARBAGE_CLEARED",
    severity: "INFO",
    status: "RESOLVED",
    started_at: ago(300),
    ended_at: ago(250),
    summary: "Garbage detection cleared after collection.",
  },
];

// ── Crews ─────────────────────────────────────────────────────────────────────

export const MOCK_CREWS: CleaningCrew[] = [
  {
    crew_id: "crew-alpha",
    name: "Alpha Team",
    status: "IN_ROUTE",
    members_count: 3,
    vehicle_id: "VEH-101",
    phone: "+381 11 123-4567",
    current_location: {
      lat: 44.8172,
      lng: 20.4588,
      accuracy_m: 8,
      heading_deg: 45,
      speed_mps: 8.3,
      updated_at: ago(0.2),
    },
    assigned_route_plan_id: "plan-001",
  },
  {
    crew_id: "crew-bravo",
    name: "Bravo Team",
    status: "AT_STOP",
    members_count: 2,
    vehicle_id: "VEH-102",
    phone: "+381 11 234-5678",
    current_location: {
      lat: 44.7901,
      lng: 20.4823,
      accuracy_m: 5,
      heading_deg: 0,
      speed_mps: 0,
      updated_at: ago(1),
    },
    assigned_route_plan_id: "plan-001",
  },
  {
    crew_id: "crew-charlie",
    name: "Charlie Team",
    status: "ON_DUTY",
    members_count: 2,
    vehicle_id: "VEH-103",
    phone: "+381 11 345-6789",
    current_location: {
      lat: 44.8412,
      lng: 20.4051,
      accuracy_m: 12,
      heading_deg: 180,
      speed_mps: 5.1,
      updated_at: ago(2),
    },
    assigned_route_plan_id: "plan-002",
  },
  {
    crew_id: "crew-delta",
    name: "Delta Team",
    status: "OFF_DUTY",
    members_count: 3,
    vehicle_id: "VEH-104",
    phone: "+381 11 456-7890",
  },
  {
    crew_id: "crew-echo",
    name: "Echo Team",
    status: "ON_BREAK",
    members_count: 2,
    vehicle_id: "VEH-105",
    current_location: {
      lat: 44.8055,
      lng: 20.4200,
      accuracy_m: 6,
      updated_at: ago(15),
    },
  },
];

// ── Route plans ────────────────────────────────────────────────────────────────

export const MOCK_ROUTE_PLANS: RoutePlan[] = [
  {
    route_plan_id: "plan-001",
    date: today,
    status: "IN_PROGRESS",
    summary: {
      vehicles_used: 2,
      stops: 8,
      estimated_distance_km: 24.5,
      estimated_duration_min: 180,
      completed_stops: 3,
      remaining_stops: 5,
    },
    routes: [
      {
        route_id: "route-001a",
        crew_id: "crew-alpha",
        vehicle_id: "VEH-101",
        status: "IN_PROGRESS",
        estimated_distance_km: 12.1,
        estimated_duration_min: 90,
        stops: [
          {
            stop_id: "stop-001",
            order: 1,
            container_id: "cont-001",
            container_name: "Trg Republike 1",
            address: "Trg Republike 1, Beograd",
            location: { lat: 44.8152, lng: 20.4584 },
            eta: ago(-30),
            service_time_min: 10,
            priority_score: 87,
            reason: ["FULL_THRESHOLD"],
            status: "COMPLETED",
            fill_pct: 87,
            fill_state: "FULL",
          },
          {
            stop_id: "stop-002",
            order: 2,
            container_id: "cont-002",
            container_name: "Knez Mihailova 12",
            address: "Knez Mihailova 12, Beograd",
            location: { lat: 44.8198, lng: 20.4566 },
            eta: from_now(10),
            service_time_min: 10,
            priority_score: 98,
            reason: ["CRITICAL_FULL", "GARBAGE_DETECTED"],
            status: "IN_PROGRESS",
            fill_pct: 96,
            fill_state: "CRITICAL",
            camera_state: "GARBAGE_DETECTED",
          },
          {
            stop_id: "stop-003",
            order: 3,
            container_id: "cont-003",
            container_name: "Terazije 5",
            address: "Terazije 5, Beograd",
            location: { lat: 44.8145, lng: 20.4602 },
            eta: from_now(30),
            service_time_min: 10,
            priority_score: 65,
            reason: ["NEAR_FULL"],
            status: "PENDING",
            fill_pct: 65,
            fill_state: "NEAR_FULL",
          },
          {
            stop_id: "stop-004",
            order: 4,
            container_id: "cont-013",
            container_name: "Dorćol — Cara Dušana 12",
            address: "Cara Dušana 12, Beograd",
            location: { lat: 44.8237, lng: 20.4640 },
            eta: from_now(55),
            service_time_min: 10,
            priority_score: 45,
            reason: ["MAINTENANCE_REQUIRED"],
            status: "PENDING",
            fill_pct: 25,
          },
        ],
      },
      {
        route_id: "route-001b",
        crew_id: "crew-bravo",
        vehicle_id: "VEH-102",
        status: "IN_PROGRESS",
        estimated_distance_km: 12.4,
        estimated_duration_min: 90,
        stops: [
          {
            stop_id: "stop-005",
            order: 1,
            container_id: "cont-007",
            container_name: "Vojvode Stepe 101",
            address: "Vojvode Stepe 101, Beograd",
            location: { lat: 44.7901, lng: 20.4823 },
            eta: ago(-10),
            service_time_min: 15,
            priority_score: 99,
            reason: ["FLAME_DETECTED", "CRITICAL_FULL", "GARBAGE_DETECTED"],
            status: "ARRIVED",
            fill_pct: 91,
            fill_state: "CRITICAL",
            camera_state: "GARBAGE_DETECTED",
          },
          {
            stop_id: "stop-006",
            order: 2,
            container_id: "cont-015",
            container_name: "Palilula — Cara Nikolaja 8",
            address: "Cara Nikolaja 8, Beograd",
            location: { lat: 44.8295, lng: 20.4852 },
            eta: from_now(45),
            service_time_min: 10,
            priority_score: 89,
            reason: ["FULL_THRESHOLD"],
            status: "PENDING",
            fill_pct: 89,
            fill_state: "FULL",
          },
          {
            stop_id: "stop-007",
            order: 3,
            container_id: "cont-011",
            container_name: "Novi Beograd — Blok 45",
            address: "Blok 45, Novi Beograd",
            location: { lat: 44.8098, lng: 20.4131 },
            eta: from_now(70),
            service_time_min: 10,
            priority_score: 85,
            reason: ["FULL_THRESHOLD", "GARBAGE_DETECTED"],
            status: "PENDING",
            fill_pct: 85,
            fill_state: "FULL",
          },
          {
            stop_id: "stop-008",
            order: 4,
            container_id: "cont-004",
            container_name: "Bulevar Kralja Aleksandra 47",
            address: "Bulevar Kralja Aleksandra 47, Beograd",
            location: { lat: 44.8098, lng: 20.4731 },
            eta: from_now(100),
            service_time_min: 10,
            priority_score: 42,
            reason: ["NEAR_FULL"],
            status: "PENDING",
            fill_pct: 42,
          },
        ],
      },
    ],
    created_at: ago(120),
    dispatched_at: ago(90),
    dispatched_by: "dispatcher@smart-waste.local",
  },
  {
    route_plan_id: "plan-002",
    date: today,
    status: "DISPATCHED",
    summary: {
      vehicles_used: 1,
      stops: 4,
      estimated_distance_km: 18.2,
      estimated_duration_min: 120,
      completed_stops: 0,
      remaining_stops: 4,
    },
    routes: [
      {
        route_id: "route-002a",
        crew_id: "crew-charlie",
        vehicle_id: "VEH-103",
        status: "DISPATCHED",
        estimated_distance_km: 18.2,
        estimated_duration_min: 120,
        stops: [
          {
            stop_id: "stop-009",
            order: 1,
            container_id: "cont-010",
            container_name: "Zemun — Cara Dušana 32",
            address: "Cara Dušana 32, Zemun",
            location: { lat: 44.8412, lng: 20.4051 },
            eta: from_now(20),
            service_time_min: 10,
            priority_score: 76,
            reason: ["NEAR_FULL"],
            status: "PENDING",
            fill_pct: 76,
          },
          {
            stop_id: "stop-010",
            order: 2,
            container_id: "cont-009",
            container_name: "Zemun — Gardoš 4",
            address: "Gardoš 4, Zemun",
            location: { lat: 44.8453, lng: 20.4012 },
            eta: from_now(40),
            service_time_min: 10,
            priority_score: 50,
            reason: ["MAINTENANCE_REQUIRED"],
            status: "PENDING",
            fill_pct: 50,
          },
          {
            stop_id: "stop-011",
            order: 3,
            container_id: "cont-014",
            container_name: "Bežanija — Tošin Bunar 85",
            address: "Tošin Bunar 85, Beograd",
            location: { lat: 44.8199, lng: 20.3820 },
            eta: from_now(60),
            service_time_min: 10,
            priority_score: 58,
            reason: ["NEAR_FULL"],
            status: "PENDING",
            fill_pct: 58,
          },
          {
            stop_id: "stop-012",
            order: 4,
            container_id: "cont-012",
            container_name: "Novi Beograd — Gandijeva 3",
            address: "Gandijeva 3, Novi Beograd",
            location: { lat: 44.8055, lng: 20.4200 },
            eta: from_now(90),
            service_time_min: 10,
            priority_score: 30,
            reason: ["NEAR_FULL"],
            status: "PENDING",
            fill_pct: 30,
          },
        ],
      },
    ],
    created_at: ago(60),
    dispatched_at: ago(30),
  },
  {
    route_plan_id: "plan-003",
    date: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    status: "COMPLETED",
    summary: {
      vehicles_used: 2,
      stops: 10,
      estimated_distance_km: 32.1,
      estimated_duration_min: 240,
      completed_stops: 10,
      remaining_stops: 0,
    },
    routes: [],
    created_at: ago(26 * 60),
    dispatched_at: ago(25 * 60),
  },
];

// ── Maintenance tickets ────────────────────────────────────────────────────────

export const MOCK_MAINTENANCE_TICKETS: MaintenanceTicket[] = [
  {
    ticket_id: "ticket-001",
    container_id: "cont-008",
    device_id: "dev-008",
    type: "CAMERA_FAULT",
    priority: "HIGH",
    status: "OPEN",
    description:
      "Camera inference failing repeatedly. Lens may be dirty or motor blocked. Requires on-site inspection.",
    created_at: ago(200),
    updated_at: ago(200),
  },
  {
    ticket_id: "ticket-002",
    container_id: "cont-006",
    device_id: "dev-006",
    type: "SENSOR_FAULT",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    description:
      "Device offline for 2+ hours despite area power being available. Possible antenna or power board issue.",
    created_at: ago(130),
    updated_at: ago(60),
    assigned_to: "tech-01",
  },
  {
    ticket_id: "ticket-003",
    container_id: "cont-007",
    type: "FLAME_SENSOR_FAULT",
    priority: "CRITICAL",
    status: "OPEN",
    description:
      "Flame detected — site needs immediate inspection. Possible arson or spontaneous combustion of waste.",
    created_at: ago(12),
    updated_at: ago(12),
    assigned_to: "tech-02",
  },
  {
    ticket_id: "ticket-004",
    container_id: "cont-009",
    type: "CALIBRATION_REQUIRED",
    priority: "LOW",
    status: "OPEN",
    description:
      "Ultrasonic sensor reading appears inconsistent. Calibration check required during next service visit.",
    created_at: ago(500),
    updated_at: ago(500),
  },
  {
    ticket_id: "ticket-005",
    container_id: "cont-005",
    type: "PHYSICAL_DAMAGE",
    priority: "LOW",
    status: "RESOLVED",
    description: "Lid hinge was cracked. Replacement done during routine maintenance.",
    created_at: ago(2 * 24 * 60),
    updated_at: ago(24 * 60),
  },
];

// ── Dashboard summary ─────────────────────────────────────────────────────────

export function buildMockDashboardSummary(): DashboardSummary {
  const active = MOCK_CONTAINERS.filter((c) => c.status === "ACTIVE");
  return {
    containers_total: MOCK_CONTAINERS.length,
    containers_near_full: active.filter(
      (c) => c.latest_state.fill_state === "NEAR_FULL"
    ).length,
    containers_full: active.filter(
      (c) => c.latest_state.fill_state === "FULL"
    ).length,
    containers_critical: active.filter(
      (c) => c.latest_state.fill_state === "CRITICAL"
    ).length,
    open_alarms: MOCK_ALARMS.filter((a) => a.status === "OPEN").length,
    critical_alarms: MOCK_ALARMS.filter(
      (a) => a.status === "OPEN" && a.severity === "CRITICAL"
    ).length,
    crews_on_duty: MOCK_CREWS.filter(
      (c) => c.status !== "OFF_DUTY"
    ).length,
    active_route_plans: MOCK_ROUTE_PLANS.filter(
      (p) => p.status === "IN_PROGRESS" || p.status === "DISPATCHED"
    ).length,
    open_tickets: MOCK_MAINTENANCE_TICKETS.filter(
      (t) => t.status === "OPEN" || t.status === "IN_PROGRESS"
    ).length,
    updated_at: new Date().toISOString(),
  };
}

// ── Telemetry ─────────────────────────────────────────────────────────────────

export function generateMockTelemetry(
  containerId: string,
  hoursBack = 24
): TelemetryPoint[] {
  const points: TelemetryPoint[] = [];
  const container = MOCK_CONTAINERS.find((c) => c.container_id === containerId);
  const baseFill = container?.latest_state.fused_fill_pct ?? 50;

  for (let i = hoursBack * 60; i >= 0; i -= 15) {
    const t = new Date(now.getTime() - i * 60 * 1000);
    const progress = 1 - i / (hoursBack * 60);
    const fill = Math.min(100, Math.max(0, baseFill - (1 - progress) * baseFill * 0.8 + Math.random() * 4 - 2));
    points.push({
      ts: t.toISOString(),
      temperature_c: +(20 + Math.sin(i / 60) * 5 + Math.random() * 2).toFixed(1),
      humidity_pct: +(60 + Math.cos(i / 60) * 10 + Math.random() * 3).toFixed(1),
      fused_fill_pct: +fill.toFixed(1),
      weight_kg: +(fill * 4.5 + Math.random() * 10).toFixed(1),
      ultrasonic_distance_cm: +(Math.max(5, 100 - fill)).toFixed(0),
      rssi_dbm: Math.floor(-70 - Math.random() * 20),
      uptime_sec: Math.floor(i * 60 + Math.random() * 1000),
    });
  }
  return points;
}
